// <auto-generated />
using System;
using CarShop26.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarShop26.Data.Migrations
{
    [DbContext(typeof(CarShop26DbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarShop26.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("FuelType")
                        .HasColumnType("int");

                    b.Property<int>("GearboxType")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Mileage")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CityId");

                    b.HasIndex("UserId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Audi",
                            CategoryId = 8,
                            CityId = 1,
                            CreatedOn = new DateTime(2026, 2, 14, 18, 13, 10, 359, DateTimeKind.Local).AddTicks(267),
                            FuelType = 1,
                            GearboxType = 1,
                            ImageUrl = "https://alarmsyst-bg.com/cdn/shop/files/audi-a4-b8-8k-facelift-2009-2015-1499x843_1024x1024.jpg?v=1747237269",
                            Mileage = 120000,
                            Model = "A4",
                            Price = 15000.00m,
                            UserId = "fe0f0881-a76d-4cd6-9a79-3f6adbd5f82f",
                            Year = 2015
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Audi",
                            CategoryId = 9,
                            CityId = 5,
                            CreatedOn = new DateTime(2026, 2, 14, 18, 13, 10, 359, DateTimeKind.Local).AddTicks(310),
                            FuelType = 1,
                            GearboxType = 1,
                            ImageUrl = "https://cdn.images.autoexposure.co.uk/AETA31676/AETV29758780_1e.jpg",
                            Mileage = 90000,
                            Model = "A3",
                            Price = 20000.00m,
                            UserId = "fe0f0881-a76d-4cd6-9a79-3f6adbd5f82f",
                            Year = 2020
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Audi",
                            CategoryId = 11,
                            CityId = 4,
                            CreatedOn = new DateTime(2026, 2, 14, 18, 13, 10, 359, DateTimeKind.Local).AddTicks(314),
                            FuelType = 0,
                            GearboxType = 0,
                            ImageUrl = "https://f7432d8eadcf865aa9d9-9c672a3a4ecaaacdf2fee3b3e6fd2716.ssl.cf3.rackcdn.com/C3312/U574/IMG_9463-large.jpg",
                            Mileage = 150000,
                            Model = "A5",
                            Price = 18000.00m,
                            UserId = "fe0f0881-a76d-4cd6-9a79-3f6adbd5f82f",
                            Year = 2018
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Audi",
                            CategoryId = 4,
                            CityId = 6,
                            CreatedOn = new DateTime(2026, 2, 14, 18, 13, 10, 359, DateTimeKind.Local).AddTicks(316),
                            FuelType = 1,
                            GearboxType = 1,
                            ImageUrl = "https://ahq-img.b-cdn.net/1122/v4461-13.jpg?width=1800",
                            Mileage = 185000,
                            Model = "A6",
                            Price = 14000.00m,
                            UserId = "fe0f0881-a76d-4cd6-9a79-3f6adbd5f82f",
                            Year = 2013
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Audi",
                            CategoryId = 4,
                            CityId = 2,
                            CreatedOn = new DateTime(2026, 2, 14, 18, 13, 10, 359, DateTimeKind.Local).AddTicks(318),
                            FuelType = 0,
                            GearboxType = 1,
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMtrUBtcK5dc8u9urUVoaWrpmd_HGtMx_OwA&s",
                            Mileage = 155000,
                            Model = "RS6",
                            Price = 90000.00m,
                            UserId = "fe0f0881-a76d-4cd6-9a79-3f6adbd5f82f",
                            Year = 2019
                        });
                });

            modelBuilder.Entity("CarShop26.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Van"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Jeep"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Cabriolet"
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "Avant"
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "Coupe"
                        },
                        new
                        {
                            Id = 6,
                            CategoryName = "Minivan"
                        },
                        new
                        {
                            Id = 7,
                            CategoryName = "Pickup Truck"
                        },
                        new
                        {
                            Id = 8,
                            CategoryName = "Sedan"
                        },
                        new
                        {
                            Id = 9,
                            CategoryName = "Hatchback"
                        },
                        new
                        {
                            Id = 10,
                            CategoryName = "SUV"
                        },
                        new
                        {
                            Id = 11,
                            CategoryName = "Sportback"
                        });
                });

            modelBuilder.Entity("CarShop26.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityName = "Sofia"
                        },
                        new
                        {
                            Id = 2,
                            CityName = "Plovdiv"
                        },
                        new
                        {
                            Id = 3,
                            CityName = "Varna"
                        },
                        new
                        {
                            Id = 4,
                            CityName = "Burgas"
                        },
                        new
                        {
                            Id = 5,
                            CityName = "Ruse"
                        },
                        new
                        {
                            Id = 6,
                            CityName = "Stara Zagora"
                        },
                        new
                        {
                            Id = 7,
                            CityName = "Pleven"
                        },
                        new
                        {
                            Id = 8,
                            CityName = "Sliven"
                        },
                        new
                        {
                            Id = 9,
                            CityName = "Dobrich"
                        },
                        new
                        {
                            Id = 10,
                            CityName = "Shumen"
                        },
                        new
                        {
                            Id = 11,
                            CityName = "Pernik"
                        },
                        new
                        {
                            Id = 12,
                            CityName = "Haskovo"
                        },
                        new
                        {
                            Id = 13,
                            CityName = "Yambol"
                        },
                        new
                        {
                            Id = 14,
                            CityName = "Pazardzhik"
                        },
                        new
                        {
                            Id = 15,
                            CityName = "Blagoevgrad"
                        },
                        new
                        {
                            Id = 16,
                            CityName = "Veliko Tarnovo"
                        },
                        new
                        {
                            Id = 17,
                            CityName = "Vratsa"
                        },
                        new
                        {
                            Id = 18,
                            CityName = "Gabrovo"
                        },
                        new
                        {
                            Id = 19,
                            CityName = "Kardzhali"
                        },
                        new
                        {
                            Id = 20,
                            CityName = "Kyustendil"
                        },
                        new
                        {
                            Id = 21,
                            CityName = "Lovech"
                        },
                        new
                        {
                            Id = 22,
                            CityName = "Montana"
                        },
                        new
                        {
                            Id = 23,
                            CityName = "Razgrad"
                        },
                        new
                        {
                            Id = 24,
                            CityName = "Silistra"
                        },
                        new
                        {
                            Id = 25,
                            CityName = "Smolyan"
                        },
                        new
                        {
                            Id = 26,
                            CityName = "Targovishte"
                        },
                        new
                        {
                            Id = 27,
                            CityName = "Vidin"
                        },
                        new
                        {
                            Id = 28,
                            CityName = "Sofia Province"
                        });
                });

            modelBuilder.Entity("CarShop26.Models.Favourites", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("UserId");

                    b.ToTable("Favourites");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "fe0f0881-a76d-4cd6-9a79-3f6adbd5f82f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f81c19fd-26e6-4bf4-b0d5-9fe7b6ab964e",
                            Email = "admin@test.bg",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@TEST.BG",
                            NormalizedUserName = "ADMIN@TEST.BG",
                            PasswordHash = "AQAAAAIAAYagAAAAEFB74yP0mW97RIoKzcDZygvxAYN1nFtEhXLWJQcfUmzxOu1U0KXyDilsf6q6/h0y+Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "YIXYIXE6GJSSN4KVYJROXMJQKQ2EVPJT",
                            TwoFactorEnabled = false,
                            UserName = "admin@test.bg"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CarShop26.Models.Car", b =>
                {
                    b.HasOne("CarShop26.Models.Category", "Category")
                        .WithMany("Cars")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarShop26.Models.City", "City")
                        .WithMany("Cars")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("City");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarShop26.Models.Favourites", b =>
                {
                    b.HasOne("CarShop26.Models.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarShop26.Models.Category", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("CarShop26.Models.City", b =>
                {
                    b.Navigation("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
